### PR TITLE
Add geonode project based setup

### PR DESCRIPTION
**Pull request by lucernae**
Add files generated from geonode-project setup.

for issue #82

### CODE REVIEW

**Comment by lucernae** [comment]
Docker image will be based on SPCGeoNode setup as it is nicely abstracted for docker/k8s

**Comment by ricardogsilva** [comment]
@lucernae 

I haven't been able to review this yet, but seems a bit odd for this PR to include 90+ files

Why would we be including all of those extra docker-related files for?

**Comment by lucernae** [comment]
@ricardogsilva I thought you want the folder to come straight from geonode-project (generated) + the development scripts. If you only have the django apps, how do you want to run them?

**Comment by ricardogsilva** [comment]
@lucernae what I meant was that it was unclear to me why we would need all these files to satisfy the task description written on #87.

I've since checked out `geonode-project` and now I understand that what you are PRing here mostly comes straight from following [their docs]. It is just I was surprised it takes 90+ files to setup a geonode project with all of their docker stuff (as an aside, in my mind this seems really bloated, in whatever way I try to frame it, but anyway...) - this was not the case the last time I used it, which admittedly was probably three years ago.

But still, if we are just keeping on scope of the issue, building the docker image would not call for all these files to be included in the PR. What it seems to me is that you are seemingly already preparing the work for #78 with this PR, not just #87. Is this assumption correct? If so, I don't mind merging it like this. But in the future please try to give me a bit more context when you submit PRs with these many files in there.

[their docs]: https://docs.geonode.org/en/master/install/advanced/project/index.html#geonode-project-installation

**Comment by lucernae** [comment]
@ricardogsilva maybe you meant issue #82 when you are talking about #87?

So what is the call? When you mentioned geonode-project I kind of assume you want the generated files to be put here (which is that many, and I thought you already know about it). We can chop off unrelated files though. I imagine we only need the extra django app and some stuff that define the requirements.

The helm charts + docker-compose  stuff is not here yet. I was planning to create another PR on top of this so it won't be jumbled up with those files.

> But in the future please try to give me a bit more context when you submit PRs with these many files in there.

Sorry, I kind of assume that you already know it will have this many files. Unless you really want to commit only some part of it, not the whole thing.

**Review by ricardogsilva — APPROVED** [review]
lookin' good :smile_cat:

**Pull request merged**
