### PR TITLE
Export styles and improve cartography

### PR DESCRIPTION
**Pull request by NyakudyaA**
* Add script to export styles from QGIS
* Script to export templates
* Add templates
* Added different styles in  the repo
*  Improve styles

**NB** If we are going to use this project for printing in the front end ie using lizmap we need to try to minimise doing geometry calculations or using  functions that are evaluated on the fly.

### CODE REVIEW

**Comment by NyakudyaA** [comment]
> This PR is quite large, which therefore makes it difficult to review. In the future please try to submit smaller PRs.

The styles are the only ones making it big
> 
>     1. I don't think we need to include the SLD files for all styles in the repo just yet, as there is no immediate necessity to have them generated. Please exclude them from the PR, or otherwise convince me of their immediate usefulness ;)

I will remove them. Since I added a script to export these styles from QGIS. Exporting them is easy but we can hold until we get the final version. My reason for including them (SLD and QGIS styles) was because it would give the ability to add and manipulate each style without having to load the full QGIS project.
> 
>     2. The intended workflow for styles in the production environment is to have them managed in a similar fashion to the actual datasets. This means:
>        
>        * Have all styles be stored in the production DB.
>        * have all styles be named according to the [resource naming conventions](https://docs.google.com/document/d/1ttyl9iSCs3uF0HEi8az77bIsZjdIae9uDgcM5P-vsjI) document. This name includes a **version** component and some other requirements.

How would you differentiate the styles at different scales ie 
Example: Ports layer has four styles with the different scales ie 50k,10k, etc

Should the layer list in the QGIS project have the same naming convention for the styles?

>        
>        Now, with that said, I understand that we do not have a production DB just yet and agree that it seems useful to store the styles in the code repo. However, if we do decide to go this way, I want to note that this shall be a temporary measure. As soon as we get the production environment set up, we will need to rename all these styles according to the naming conventions document AND we will need to save them in the production DB, in order to do a proper handout to the client. This also means that the QGIS project will need to be updated so that all styles are coming from the DB and not from repository files.
>        Alternatively, I would suggest that @NyakudyaA and @zacharlie get together and consider if saving these styles in the same GeoPackage file that we are currently using to emulate the production DB might be more suitable for this project in the medium term, as it may facilitate the migration to the production DB, when we have it.
>        Please let me know you thoughts on this before we go forward with the merging.

Currently, the styles are being saved in the QGIS project and even in the final handover if the styles are being stored in the PostgreSQL DB I still think it is a good measure to have the styles stored in the repo and we run the export script on closing the project.

Some thoughts about saving the styles in the DB. 
* It's very easy to overwrite the styles.
* We cannot revert back to a last known working style if someone has made changes.
* We need to also add rules ie Permission matrix for the layer storing the styles in QGIS.
* Even if we have proper DB roles for the layer styles we would need an audit trail for that table. Suppose two people with write access to the table write to it. Their changes will overwrite each other
* If we go with storing the styles in the geopackage we would need to also add the data to the repo
* Storing the styles as files will also open up our work to be usable with other software stacks ie MapServer, GeoServer, etc

We could write a macro that calls the export script for all styles on closing the QGIS project. Anyone with access to the repo will then push the changes for the styles

**Comment by ricardogsilva** [comment]
> How would you differentiate the styles at different scales ie
Example: Ports layer has four styles with the different scales ie 50k,10k, etc

By naming them differently, in the same way as it is being done at the moment.

Please take a look at both these documents, which detail how naming and versioning of all DomiNode resources (including styles) shall work:

- https://docs.google.com/document/d/1ttyl9iSCs3uF0HEi8az77bIsZjdIae9uDgcM5P-vsjI/
- https://docs.google.com/document/d/1KhOmdEJsJYuKyOPhO-CdALWWWQvHlQqEYtJo4SuHau0/

You are very much welcome to review and comment on those too :wink: 

---

> - It's very easy to overwrite the styles.
> - We cannot revert back to a last known working style if someone has made changes.

While I understand your point and agree with it, for this project I'm trying to go with a simpler solution. Let's provide a clear workflow for managing styles. 

Styles shall have a version attached to their name and each modification (past the original creation work) shall always be saved under a new version.

The fundamental approach that I am trying to promote here is to manage styles in a similar way as they will be managing their data and their metadata.

---

> - We need to also add rules ie Permission matrix for the layer storing the styles in QGIS.

I agree. The current plan is to only provide write access to special (i.e. the style custodian) DB users. I would like to also explore using row-level permissions in the style table, but this is still TBD.

---

> - Even if we have proper DB roles for the layer styles we would need an audit trail for that table. Suppose two people with write access to the table write to it. Their changes will overwrite each other

This problem is out of scope for the current implementation. 

I do agree that my solution is not robust and that your proposal makes more sense for a more generic case. However, my working assumptions are:

- All work on layer styles shall be coordinated by a responsible agent, which is the style custodian for the dataset;
- The number of people working on the same style, shall usually be just one. Even if multiple people work on the same style, at the same time, I don't expect them to be from different departments. Therefore, I don't expect there to be communication gaps regarding who is working on a specific style at any given time
- The universe of users that will be doing this work is likely comprised exclusively of people that are not very technical minded, so I'd like to spare them having to learn additional tools (in this case git) in order to be able to do their GIS work

So, with this mindset, I believe the workflow being devised forms a good basis for an effective management of data, styles and datasets.

We also have a document where I am describing the complete data management workflows. The styling part is still very much missing and I would appreciate your input on it. But keep in mind the general spirit of the solution that we are proposing is based on the restrictions I enumerated above.

https://docs.google.com/document/d/1rcoH0c1RpCguuPFLe92V-2xdipJU9ODwItOS_XPe-GM/

---

> - If we go with storing the styles in the geopackage we would need to also add the data to the repo

The geopackage is currently being shared off-repo (we should put it in our internal minIO sooner rather than later though). All data currently being used for the topo maps resides on this geopackage too, so it is effectively emulating the production DB.

---

> - Storing the styles as files will also open up our work to be usable with other software stacks ie MapServer, GeoServer, etc

Yes, we will definitely use SLD styles to theme GeoServer layers. However, there is currently no plan to serve the full topo maps via GeoServer (they  shall be generated offline in QGIS Desktop and will likely be fed into GeoNode, as documents, with proper versioning). 

We will be serving individual layers via GeoServer, possibly with some of the same styles used for the topomaps. But lets keep it simple, one style per layer. For this reason I think we may export the QGIS style from the DB onto an SLD file when needed (i.e. at the time the relevant layer is being published via GeoServer - That is one of the reasons I requested the SLD files be taken out of this PR).

**Review by ricardogsilva — APPROVED** [review]
Seems good to me

**Comment by zacharlie** [comment]
I have reviewed the map project and have a few issues with inconsistencies between styles at different scales. Primarily I think this stems from the initial styles at various scales being inconsistent when they were stored in distinct layer groups, which was carried through when converting into distinct styles for the layers at various scales. The remedial actions will need o be discussed further before we can merge this.

**Comment by zacharlie** [comment]
I am taking ownership of the issues I have raised with this so will be merging this

**Pull request merged**
