### PR TITLE
Add topomaps app

### LINKED ISSUE #128: Implement dominode_topomaps django application
Following the design done in #127, implement the `dominode_topomaps` django application. This app shall mediate topomap sheet downloads, making user users have the correct authorization to get them

### PR DESCRIPTION
**Pull request by ricardogsilva**
This PR adds a new django app called `dominode_topomaps`. This app is used for managing downloads of published topomap series.

It implements the design shown in #127 

Fixes #128

### CODE REVIEW

**Comment by lucernae** [comment]
@ricardogsilva the included templates for the topomaps have validation objects in it. Was it just a skeleton and should be deleted and replaced with logic to show the topomaps and sheets only?

**Comment by ricardogsilva** [comment]
> @ricardogsilva the included templates for the topomaps have validation objects in it. Was it just a skeleton and should be deleted and replaced with logic to show the topomaps and sheets only?

Yeah I had copied them from the `dominode_validation` app just as a quick skeleton. Please modify them at will

**Comment by lucernae** [comment]
# The changelist 

(feel free to suggest change if needed):

1. I revert back the navbar styles to original GeoNode for Data, with menu Layers and Topomaps (the new app)

image

2. Topomaps list will list layers that with the attribute `title` that follows our prefix pattern. I'm using `title` attribute because the `name` attribute might be fixed after upload/sync and can't be changed unless we delete and recreate the layer.

image

3. Clicking the topomap layer will navigate to the sheets list. The list will only shows sheets that have the pdf in the filesystem. Some idea that comes up from me: we could just show detected paper type lists as download button in this view (for each available sheet). That way we don't have to navigate further.

image

4. Clicking the topomap sheet from previous view will navigate to the download link list, where each available pdf file corresponds to the paper types (A1, A2, etc). We only shows detected paper type available in the filesystem (by available pdf filename).

If you don't have permission, the list and download button will be disabled (the route will return 403). This view feels a little bit redundant, that's why I was thinking that maybe it could be merged with the previous view.

With no user permission:
image

With user perrmisson:
image


# Some improvements ideas

1. We could add bootstrap badge for the number of sheets available in the ivew.
2. Where is this view/template located? I want to hook it up into the sheet page:

image

**Comment by ricardogsilva** [comment]
Looking good @lucernae!

Some remarks:

1.
> I revert back the navbar styles to original GeoNode for Data, with menu Layers and Topomaps (the new app)

Looks great!

2.
> Some idea that comes up from me: we could just show detected paper type lists as download button in this view (for each available sheet). That way we don't have to navigate further

OK, I think that is a good idea. We could use bootstrap `label` elements to show download links, as done in the `dominode_validation` app:

Screenshot from 2020-10-27 09-57-01

So this means that there will be no sheet detail view. 

These download buttons should be disabled in case the user is not allowed to download - in addition, the actual download view must also check for permissions (in case user accesses the download URL directly)


3. 

I don't like the breadcrumb navigation elements too much here. It looks strange because the rest of the GUI does not use this. Additionally, if we skip implementation of the sheet detail page (as discussed in the previous point) there will be only two levels of navigation (topomap list -> topomap detail), so breadcrumbs become unnecessary

4. 

Thinking about it I guess it would be nice to show a map viewer in the topomap detail page with the current topomap layer. This would give some useful context to users about the spatial location of each sheet. This is an extra nicety, so lets focus on the other things first and implement it only if we have the time

**Comment by ricardogsilva** [comment]
> Where is this view/template located? I want to hook it up into the sheet page

There is no template for that. It must be specified as a layer property. Look into `geonode.layers.models.Layer.feature_info_custom_template` and also these [docs](https://docs.geonode.org/en/master/usage/managing_maps/exploring_maps/get_fetureinfo.html).

This means that we'd need to change every layer (at import time), so adding some custom logic to the code that does the GeoServer sync, or maybe some signal. Let's not do it for now, as it adds some additional complexity.

**Comment by lucernae** [comment]
New changes:

image

- removed breadcrumb
- showed paper size list as downloadable link (was the color okay? I used label-default)

I still have weird problem. For some reasons, I can't unassign the permissions to check that the view blocks the download link.

**Comment by ricardogsilva** [comment]
> showed paper size list as downloadable link (was the color okay? I used label-default)

color seems a bit muted for a download link. Please switch to the `label-primary` class, which I think it should be the same blue as the one in that `back to topomaps list` buton above (as shown in the screenshot)

**Comment by lucernae** [comment]
Changes:
- Can download:

image

- download disabled (cursor won't change at hover):

image

- setting layer object permissions thru Django Admin page of GuardedModelAdmin

image

**Comment by lucernae** [comment]
Ah, I should put the name of the layer since we deleted the breadcrumb. Will do it in the next commit.

**Comment by ricardogsilva** [comment]
IMO this PR is now ready to merge, pending @lucernae's review

**Comment by lucernae** [comment]
I've seen the screencast. Looks way better! LGTM

**Pull request merged**
